### ISSUE TITLE
Cannot Find Chem4Word.Font.DLL

### ISSUE THREAD

**Issue by Quphoria** [Chem4Word/Version2#1]
The link in the build guide for Chem4Word.Font.DLL
is no longer active

The link:
http://research.microsoft.com/en-us/downloads/afbe4907-66bc-4d02-95e2-263c2bbea341

Can you add a new link or upload it to the repository

**Comment by MikeWilliams-UK** [comment]
Instructions are old and have not been updated.
Font dll is at https://github.com/Chem4Word/Version2/tree/master/dev/Libs

**Comment by MikeWilliams-UK** [comment]
@TNT-Samuel if you are using Windows 7+ and Word 2010 + you should be using V3 not V2

**Comment by Quphoria** [comment]
Thanks, I would love to use version 3, however I'm a cheapskate so I don't want to upgrade from office 2007 pro plus.
Thanks for your help.
